### ISSUE TITLE
ERROR: LoadError: GeneticVariation.VCF.Reader file format error - unexpected metainfo line from GATK command line

### ISSUE THREAD

**Issue by gtollefson** [BioJulia/GeneticVariation.jl#18]
I receive the following LoadError when reading a VCF file using `VCF.Reader(open(vcf_filename, "r"))`:

> ERROR: LoadError: GeneticVariation.VCF.Reader file format error on line 31
> Stacktrace:
>  [1] _readheader!(::GeneticVariation.VCF.Reader, ::BioCore.Ragel.State{BufferedStreams.BufferedInputStream{IOStream}}) at /Users/George/.julia/test/v0.6/BioCore/src/ReaderHelper.jl:106
>  [2] GeneticVariation.VCF.Reader(::BufferedStreams.BufferedInputStream{IOStream}) at /Users/George/.julia/test/v0.6/GeneticVariation/src/vcf/reader.jl:15
>  [3] GeneticVariation.VCF.Reader(::IOStream) at /Users/George/.julia/test/v0.6/GeneticVariation/src/vcf/reader.jl:28
>  [4] include_from_node1(::String) at ./loading.jl:576
>  [5] include(::String) at ./sysimg.jl:14
>  [6] process_options(::Base.JLOptions) at ./client.jl:305
>  [7] _start() at ./client.jl:371
> while loading /Users/George/projects_code/ViVa_use.jl/viva_cli.jl, in expression starting on line 132

I believe the code may not expect the following metainfo line that seems to have been included by the GATK command line during variant calling. Can you help identify why this error came up? Is there a way for me to read this vcf file as a reader object? The offending vcf metainfo line is pasted here:

> ##GATKCommandLine.ApplyRecalibration.2=<ID=ApplyRecalibration,Version=3.8-1-0-gf15c1c3ef,Date="Sat Jul 28 10:09:51 GMT 2018",Epoch=1532772591323,CommandLineOptions="analysis_type=ApplyRecalibration input_file=[] showFullBamList=false read_buffer_size=null read_filter=[] disable_read_filter=[] intervals=null excludeIntervals=null interval_set_rule=UNION interval_merging=ALL interval_padding=0 reference_sequence=/gpfs/data/cbc/references/ftp.broadinstitute.org/bundle/hg19/ucsc.hg19.fasta nonDeterministicRandomSeed=false disableDithering=false maxRuntime=-1 maxRuntimeUnits=MINUTES downsampling_type=BY_SAMPLE downsample_to_fraction=null downsample_to_coverage=1000 baq=OFF baqGapOpenPenalty=40.0 refactor_NDN_cigar_string=false fix_misencoded_quality_scores=false allow_potentially_misencoded_quality_scores=false useOriginalQualities=false defaultBaseQualities=-1 performanceLog=null BQSR=null quantize_quals=0 static_quantized_quals=null round_down_quantized=false disable_indel_quals=false emit_original_quals=false preserve_qscores_less_than=6 globalQScorePrior=-1.0 secondsBetweenProgressUpdates=10 validation_strictness=SILENT remove_program_records=false keep_program_records=false sample_rename_mapping_file=null unsafe=null use_jdk_deflater=false use_jdk_inflater=false disable_auto_index_creation_and_locking_when_reading_rods=false no_cmdline_in_header=false sites_only=false never_trim_vcf_format_field=false bcf=false bam_compression=null simplifyBAM=false disable_bam_indexing=false generate_md5=false num_threads=1 num_cpu_threads_per_data_thread=1 num_io_threads=0 monitorThreadEfficiency=false num_bam_file_handles=null read_group_black_list=null pedigree=[] pedigreeString=[] pedigreeValidationType=STRICT allow_intervals_with_unindexed_bam=false generateShadowBCF=false variant_index_type=DYNAMIC_SEEK variant_index_parameter=-1 reference_window_stop=0 phone_home= gatk_key=null tag=NA logging_level=INFO log_to_file=null help=false version=false input=[(RodBinding name=input source=/gpfs/data/cbc/uzun/wes_analysis/intermediary_files/all_100_v2_recalibrated_snps_raw_indels.vcf)] recal_file=(RodBinding name=recal_file source=/gpfs/data/cbc/uzun/wes_analysis/intermediary_files/all_100_v2_recalibrate_INDEL.recal) tranches_file=/gpfs/data/cbc/uzun/wes_analysis/intermediary_files/all_100_v2_recalibrate_INDEL.tranches out=/gpfs/data/cbc/uzun/wes_analysis/intermediary_files/all_100_v2_recalibrated_variants.vcf ts_filter_level=95.0 useAlleleSpecificAnnotations=false lodCutoff=null ignore_filter=null ignore_all_filters=false excludeFiltered=false mode=INDEL filter_reads_with_N_cigar=false filter_mismatching_base_and_quals=false filter_bases_not_stored=false">

I would include the vcf file with this line for reproducibility, but it is very large. 

I am writing a tool for vcf analysis that I would like to be able to read vcf files in a variety of formats, so it's important to me to be able to load a file like this. 

I am running Julia 0.6.4. 

Thank you!

**Comment by TransGirlCodes** [comment]
Hi @gtollefson, does it work with the file if you eliminate the offending metainfo from it?

**Comment by gtollefson** [comment]
@BenJWard Thanks for your response. I will try this asap. I haven't gotten a chance yet.

I'm very suspicious it is this metainfo line because GATK recently updated from v3 to v4 and there were major syntax changes affecting the command line. The offending line is from the GATK command line.

I will try to edit the vcf file asap to try.

**Comment by gtollefson** [comment]
@BenJWard This issue has occurred on all vcf files I've attempted to load created with GATK v4. These all contain this GATK command line metainfo header line.

**Comment by gtollefson** [comment]
@BenJWard I'm having a hard time removing this line from the vcf file. I'm trying variations of `egrep -vwE "^##GATK" all_recalibrated_variants.vcf > removed_gatk_all_combined_variants_50.vcf` but the line is still there. Do you have any suggestions?

**Comment by gtollefson** [comment]
@BenJWard This error has occurred when loading other vcf files with this line as well, just fyi.

**Comment by gtollefson** [comment]
@BenJWard , I've removed the line from the file and now it does work. It looks like it was that line. 

GATK updated to version 4 recently and introduced syntax changes that I know disrupted a lot of workflows. Perhaps there were some syntax changes shortly before as well as this was run on GATK 3.8.

This problem is important for us to fix because the tool we are hoping to release in a few weeks depends heavily on the reader function.

**Comment by gtollefson** [comment]
[example_offending_vcf_for_Ben.vcf.zip](https://github.com/BioJulia/GeneticVariation.jl/files/2443967/example_offending_vcf_for_Ben.vcf.zip)
