### ISSUE TITLE
1.0 Support

### ISSUE THREAD

**Issue by dialvarezs** [BioJulia/GeneticVariation.jl#20]
Hi, great work with this package and BioJulia overall!
I'm new on Julia and I started using 1.0. In a part of my program I need to read some VCFs, and this package doesn't work on 1.0 (#master installs but fails at precompilation). For now I'm using PyCall+pyvcf, but that's a bit ugly.
Do you have plans to support 1.0? What needs to be done for that? I'm learning Julia but I have experience with C and Python, so I could try to make the modifications if you don't have time now.

Thanks!

**Comment by TransGirlCodes** [comment]
Hi @dialvarezs support for julia 1.0 is planned, and is currently being implemented on the `GATK-fix` branch, which will have 1.0 updates and a bugfix. I should be done with it very soon, I'll post here and let you know when I've done it.

**Comment by TransGirlCodes** [comment]
Hi @dialvarezs the updates to julia v1.0 and the bugfix are now complete. I will be merging and cutting a release in the next few hours. Then you'll have to wait for it to come through METADATA but that shouldn't be long.

**Comment by dialvarezs** [comment]
Great job @BenJWard. Thank you so much!
