### ISSUE TITLE
Add Project.toml

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/GeneticVariation.jl#29]
There's no Project.toml. I've never used this package, and so don't have the knowledge of what packages are needed for this package to run.

**Comment by pfarndt** [comment]
Still no `Project.toml` - is this package still maintained?

**Comment by TransGirlCodes** [comment]
@pfarndt It is maintained, but it is less maintained than other packages as we all prioritise our dev/maintainer time. It is due for an overhaul like some of the other packages like BioSequences and BioAlignments, where the file format parsers were extracted out into their own packages, so there is a VCF.jl due. But it's as time allows vs. other packages and projects.

**Comment by rasmushenningsson** [comment]
I've made a pull request #31 to add Project.toml.

**Comment by CiaranOMara** [comment]
#31 was merged.
